### ISSUE TITLE
How to get the ground truth images

### ISSUE THREAD

**Issue by SkyeLu** [csjunxu/PolyUDataset#4]
Hi Jun, Thanks for you work! I have downloaded this dataset, it seems that each folder contains 100 images, I am confused that which is the ground truth and which is the noisy image. Could you help me? Thanks a lot!

**Comment by SkyeLu** [comment]
I realize that I should just download 'OriginalImages' .

**Comment by csjunxu** [comment]
Great, you find the answer!

Best Regards!

All my best wishes!

Jun Xu


SkyeLu <notifications@github.com> 于2020年5月7日周四 下午5:05写道：
