### ISSUE TITLE
PanBaidu

### ISSUE THREAD

**Issue by SolicTous** [csjunxu/PolyUDataset#8]
Can anybody get me Dataset on GDrive or Mega, not PanBaidu... It's impossible to create an account if your country is not China.

**Comment by csjunxu** [comment]
Sorry for it. I will copy the data to GDrive and provide the link.

**Comment by SolicTous** [comment]
That will be nice))

**Comment by csjunxu** [comment]
Hi, Marsel

Finaaaaaally, I upload the dataset to GDrive at
https://drive.google.com/file/d/1tzNY-WTk3HRI8MiixDp1-Es1k55VgRKS/view?usp=sharing

Hope it helps you!

Best Regards!

All my best wishes!

Jun Xu


Marsel Iamaev ***@***.***> 于2021年9月15日周三 下午6:25写道：

**Comment by SolicTous** [comment]
Thank you, csjunxu. Really, I've surprised with your attention)
Is it the correct opinion that *mean.jpg is a Sum of all images in one directory and dividing by the amount of them?

I will try to find by pnsr/ssim the noisiest and make pairs))

**Comment by csjunxu** [comment]
Yes! The mean images are usually taken as the ground-truths.
